module.exports = [
  {
    VIN: "5TFCY5F13DX037205",
    make: "BMW",
    model: "530",
    mileage: "9400",
    title_status: "rebuilt",
    transmission_type: null,
  },
  {
    VIN: "4T1BF3EK9BU816988",
    make: "Ford",
    model: "Tempo",
    mileage: "97800",
    title_status: "affidavit",
    transmission_type: null,
  },
  {
    VIN: "19UUA75528A734691",
    make: "BMW",
    model: "5 Series",
    mileage: "79100",
    title_status: "affidavit",
    transmission_type: "automatic",
  },
  {
    VIN: "WP0AA2A95CS941575",
    make: "Ferrari",
    model: "F430",
    mileage: "8900",
    title_status: "affidavit",
    transmission_type: null,
  },
  {
    VIN: "2HNYD2H67DH052698",
    make: "Volkswagen",
    model: "Cabriolet",
    mileage: "924700",
    title_status: "rebuilt",
    transmission_type: "manual",
  },
  {
    VIN: "1G4PT5SV8F4722521",
    make: "GMC",
    model: "Jimmy",
    mileage: "97000",
    title_status: "affidavit",
    transmission_type: null,
  },
  {
    VIN: "WBALM5C52BE086145",
    make: "Ford",
    model: "Explorer",
    mileage: "9700",
    title_status: "affidavit",
    transmission_type: "manual",
  },
  {
    VIN: "1FTMF1E82AF920115",
    make: "Porsche",
    model: "944",
    mileage: "9300",
    title_status: "rebuilt",
    transmission_type: "automatic",
  },
  {
    VIN: "WAUET48H96K029280",
    make: "Honda",
    model: "Accord",
    mileage: "97500",
    title_status: "affidavit",
    transmission_type: "manual",
  },
  {
    VIN: "1GYFK13279R073540",
    make: "Ford",
    model: "Mustang",
    mileage: "662600",
    title_status: "affidavit",
    transmission_type: null,
  },
];
